#### 1. Выберите те наборы векторов, которые являются линейно независимыми (один вектор тоже считается набором).

**(1,0),(1,1)** Нельзя сложить эти два вектора с ненулевыми коэффициентами и получить нулевой вектор.

**(1,0)** Набор из одного вектора всегда является линейно независимым (кроме случая, когда это нулевой вектор).

**(1,0),(0,1)** Нельзя сложить эти два вектора с ненулевыми коэффициентами и получить нулевой вектор.

(1,0),(0,1),(−1,1)

#### 2. Чему равна манхэттенская норма вектора a=(−1,2,−1)?

$$
 \left\Vert a \right\Vert_{1} = \sum_{i=1}^n \left| a_{i} \right| = \left| -1 \right| + \left| 2 \right| + \left| -1 \right| = 4
$$

#### 3. Чему равно скалярное произведение векторов a=(1,2,3) и b=(−3,1,1)?

$$
\langle a, b \rangle = \sum_{i=1}^n a_{i} b_{i}.
 = 1*(-3) + 2*1 + 3*1 = -3 +2 +3 = 2
$$

In [28]:
import numpy
a = numpy.array([1, 2, 3])
b = numpy.array([-3, 1, 1])
print a, b
a.dot(b)


[1 2 3] [-3  1  1]


2

#### 4. В пространствах какой размерности можно выбрать k линейно независимых векторов?

k - 1  
**k + 1**  
**k**  

Объяснение: Максимальное число линейно независимых векторов в линейном
пространстве V назывется размерностью и равно $ dim\mathbb{R}^n = n$.
Значит если мы подставим k, то только в пространствах с размерностью >= k мы сможем выбрать k линейно независимых векторов.

#### 5. Какие из нижеприведенных команд корректно отработают и создадут вектор?

**f = numpy.arange(1, 2, 0.3, dtype=float)**

**b = numpy.array([1, 2, 3, 4, 5], dtype=float)**

**c = numpy.array([False, False, True])**

b = numpy.array(1, 2, 3, 4, 5, dtype=float)

#### 6. Пусть даны два вектора a = numpy.array([6, 3, -5]) и b = numpy.array([-1, 0, 7]). Какая из следующих команд считает евклидово расстояние между этими векторами?

**scipy.spatial.distance.cdist(a[numpy.newaxis, :], b[numpy.newaxis, :], metric='euclidean')**

numpy.linalg.norm(a, ord=2) - np.linalg.norm(b, ord=2)

scipy.spatial.distance.cdist(a[:, numpy.newaxis], b[:, numpy.newaxis], metric='euclidean')

scipy.spatial.distance.cdist(b, a, metric='euclidean')

In [11]:
import scipy.spatial.distance

In [29]:
a = numpy.array([6, 3, -5])
b = numpy.array([-1, 0, 7])
print a, b
print a.shape, b.shape
print a[numpy.newaxis, :], b[numpy.newaxis, :]
print a[numpy.newaxis, :].shape, b[numpy.newaxis, :].shape

[ 6  3 -5] [-1  0  7]
(3,) (3,)
[[ 6  3 -5]] [[-1  0  7]]
(1, 3) (1, 3)


In [12]:
scipy.spatial.distance.cdist(a[numpy.newaxis, :], b[numpy.newaxis, :], metric='euclidean')

array([[ 14.2126704]])

#### 7. Пусть даны два вектора a = numpy.array([0, -1, 11]) и b = numpy.array([3, 7, 2]). Какие из следующих команд считают скалярное произведение этих векторов?

**numpy.dot(a, b)**

**b.dot(a)**

numpy.dot(a, b) / numpy.linalg.norm(a) / numpy.linalg.norm(b) - это формула используется для расчета угла между a и b

a * b

#### 8. Пусть дан вектор a = numpy.array([8, 10, -1, 0, 0]). Какие из следующих команд преобразуют вектор a к вектор-столбцу?

**a = a.reshape((5, 1))**

a = a.reshape((1, 5))

**a = a[:, numpy.newaxis]**

a = a[numpy.newaxis, :]

In [25]:
a = numpy.array([8, 10, -1, 0, 0])
print a
a.shape

[ 8 10 -1  0  0]


(5,)

In [27]:
a.reshape((5, 1))

array([[ 8],
       [10],
       [-1],
       [ 0],
       [ 0]])

In [18]:
a.reshape((1, 5))

array([[ 8, 10, -1,  0,  0]])

In [21]:
a[:, numpy.newaxis]

array([[ 8],
       [10],
       [-1],
       [ 0],
       [ 0]])

In [22]:
a[numpy.newaxis, :]

array([[ 8, 10, -1,  0,  0]])